# Generated by Django 2.2.17 on 2021-02-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': '文章', 'verbose_name_plural': '文章列表'},
        ),
    ]
